name: env
description: A repository that manages environmental variables.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  envied: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
